<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <LangVersion>13</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FileFlow.Sdk\FileFlow.Sdk.csproj" />
    <ProjectReference Include="..\FileFlow.Core\FileFlow.Core.csproj" />
    <ProjectReference Include="..\FileFlow.Plugin.FileSystem\FileFlow.Plugin.FileSystem.csproj" />
    <ProjectReference Include="..\FileFlow.Plugin.Archives\FileFlow.Plugin.Archives.csproj" />
    <ProjectReference Include="..\FileFlow.Plugin.Images\FileFlow.Plugin.Images.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="Nodify" Version="3.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.2" />
  </ItemGroup>

  <Target Name="CopyPlugins" AfterTargets="Build">
    <MakeDir Directories="$(OutDir)Plugins" />
    <ItemGroup>
      <PluginFiles Include="..\FileFlow.Plugin.FileSystem\bin\$(Configuration)\net9.0\*.*" />
      <PluginFiles Include="..\FileFlow.Plugin.Archives\bin\$(Configuration)\net9.0\*.*" />
      <PluginFiles Include="..\FileFlow.Plugin.Images\bin\$(Configuration)\net9.0\*.*" />
    </ItemGroup>
    <Copy SourceFiles="@(PluginFiles)" DestinationFolder="$(OutDir)Plugins\" SkipUnchangedFiles="true" />
  </Target>
</Project>
